spring:
  datasource:
    url: jdbc:mysql://116.62.222.151:3306/crm?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  application:
    name: mp


